# Generated by Django 5.2.8 on 2025-11-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Task title/description', max_length=200)),
                ('due_date', models.DateField(blank=True, help_text='When is the task due? (YYYY-MM-DD)', null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete the task, e.g., 2.5 hours', max_digits=5, null=True)),
                ('importance', models.IntegerField(default=5, help_text='Rate the task importance out of 10')),
                ('dependencies', models.CharField(blank=True, default='', help_text="Comma-separated list of task IDs this task depends on (e.g., '1,3,5')", max_length=500)),
                ('completed', models.BooleanField(default=False, help_text='Has this task been completed?')),
            ],
        ),
    ]
